
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.universidad.appproyecto1.analisis.analisisCopy;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 7;
  public static final int STRING = 5;
  public static final int error = 1;
  public static final int DIRECTORIO_DEF = 4;
  public static final int NOMBRE_PROYECTO = 2;
  public static final int DIRECTORIO_JSON = 3;
  public static final int EOF = 0;
  public static final int DOS_PUNTOS = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NOMBRE_PROYECTO",
  "DIRECTORIO_JSON",
  "DIRECTORIO_DEF",
  "STRING",
  "DOS_PUNTOS",
  "COMA"
  };
}

