
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.universidad.servidorproyecto1.analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int error = 1;
  public static final int COMENTARIO_LINEA = 2;
  public static final int COMENTARIO_MULTILINEA = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMENTARIO_LINEA",
  "COMENTARIO_MULTILINEA"
  };
}

