
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.universidad.appproyecto1.analisis.analisisJSON;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int L_LLAVE = 6;
  public static final int COMA = 2;
  public static final int TRUE = 8;
  public static final int NULL = 10;
  public static final int STRING = 12;
  public static final int EOF = 0;
  public static final int R_LLAVE = 7;
  public static final int L_CORCHETE = 4;
  public static final int NUMERO = 11;
  public static final int FALSE = 9;
  public static final int error = 1;
  public static final int DOS_PUNTOS = 3;
  public static final int R_CORCHETE = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "DOS_PUNTOS",
  "L_CORCHETE",
  "R_CORCHETE",
  "L_LLAVE",
  "R_LLAVE",
  "TRUE",
  "FALSE",
  "NULL",
  "NUMERO",
  "STRING"
  };
}

