/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.universidad.appproyecto1.interfaz;

import java.io.IOException;
import java.net.ConnectException;
import java.net.Socket;

import javax.swing.UIManager;

import com.universidad.appproyecto1.api.*;
import com.universidad.appproyecto1.exceptions.NoArchivoException;

/**
 *
 * @author fernanrod
 */
public class Interfaz extends javax.swing.JFrame {
    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarkLaf");
        } catch (Exception e) {
            System.err.println("Failed to initialize LaF");
        }
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        analizarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        seleccionDirectorioButton1 = new javax.swing.JButton();
        seleccionDirectorioButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        archivoSeleccionadoLabel1 = new javax.swing.JLabel();
        archivoSeleccionadoLabal2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        analizarButton.setText("Analizar");
        analizarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analizarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Primer Proyecto");

        jLabel2.setText("Segundo Proyecto");

        seleccionDirectorioButton1.setText("Seleccionar Directorio");
        seleccionDirectorioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionDirectorioButton1ActionPerformed(evt);
            }
        });

        seleccionDirectorioButton2.setText("Seleccionar Directorio");
        seleccionDirectorioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionDirectorioButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Archivo Seleccionado:");

        jLabel4.setText("Archivo Seleccionado:");

        archivoSeleccionadoLabel1.setText("No se ha seleccionado");
        archivoSeleccionadoLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        archivoSeleccionadoLabel1.setMaximumSize(new java.awt.Dimension(210, 28));

        archivoSeleccionadoLabal2.setText("No se ha seleccionado");
        archivoSeleccionadoLabal2.setMaximumSize(new java.awt.Dimension(210, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(seleccionDirectorioButton1)
                    .addComponent(jLabel3)
                    .addComponent(archivoSeleccionadoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(seleccionDirectorioButton2)
                    .addComponent(jLabel4)
                    .addComponent(archivoSeleccionadoLabal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(analizarButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleccionDirectorioButton1)
                    .addComponent(seleccionDirectorioButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archivoSeleccionadoLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(archivoSeleccionadoLabal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(analizarButton)
                .addGap(129, 129, 129))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionDirectorioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionDirectorioButton1ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.showOpenDialog(this);
        
        java.nio.file.Path directorio = fileChooser.getSelectedFile().toPath();
        try {
            ManejadorProyectos.seleccionarProyecto(directorio, 1);
            javax.swing.JOptionPane.showMessageDialog(this, "Se ha seleccionado el proyecto exitosamente");
            String nombreArchivo = directorio.toString().split("/")[directorio.toString().split("/").length-1];
            archivoSeleccionadoLabel1.setText(nombreArchivo);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ha ocurrido un error al seleccionar el directorio");
            e.printStackTrace();
        }
    }//GEN-LAST:event_seleccionDirectorioButton1ActionPerformed

    private void analizarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analizarButtonActionPerformed
        // TODO add your handling code here:
        try {
            ManejadorProyectos.enviarArchivo();
            javax.swing.JOptionPane.showMessageDialog(this, "Se han enviado y analizado los proyectos");
        } catch (ConnectException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se ha podido conectar al servidor");
            e.printStackTrace();
        } catch (IOException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ha ocurrido un error al enviar los proyectos");
            e.printStackTrace();
        } catch (NoArchivoException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: Falta seleccionar uno o dos proyectos para su analisis");
            e.printStackTrace();
        }
    }//GEN-LAST:event_analizarButtonActionPerformed

    private void seleccionDirectorioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionDirectorioButton2ActionPerformed
        // TODO add your handling code here:
        javax.swing.JFileChooser fileChooser = new javax.swing.JFileChooser();
        fileChooser.showOpenDialog(this);
        
        java.nio.file.Path directorio = fileChooser.getSelectedFile().toPath();
        try {
            ManejadorProyectos.seleccionarProyecto(directorio, 2);
            javax.swing.JOptionPane.showMessageDialog(this, "Se ha seleccionado el proyecto exitosamente");
            String nombreArchivo = directorio.toString().split("/")[directorio.toString().split("/").length-1];
            archivoSeleccionadoLabal2.setText(nombreArchivo);
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Ha ocurrido un error al seleccionar el directorio");
            e.printStackTrace();
        }
    }//GEN-LAST:event_seleccionDirectorioButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizarButton;
    private javax.swing.JLabel archivoSeleccionadoLabal2;
    private javax.swing.JLabel archivoSeleccionadoLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton seleccionDirectorioButton1;
    private javax.swing.JButton seleccionDirectorioButton2;
    // End of variables declaration//GEN-END:variables
}
